version: '3'
services:
  web:
    # Use the image from the Docker registry
    image: ghcr.io/xbaloyi/astt-cam-software-test
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: /app/src/astt_gui/app.py
    command: flask run --host=0.0.0.0 --port=5000
