version: '3'
services:
  web:
    image: ghcr.io/xbaloyi/astt-cam-software-test:latest
    container_name: ASTTSoftware_GUI
    ports:
      - "5000:5000"
    networks: 
      - astt_network
    command: flask run --host=0.0.0.0 --port=5000
    
networks:
   astt_network:
    driver: bridge
